Further file fragment fixes
gregsdennis/json-everything pull request #430
Opened 2023-04-13 01:46 UTC by faldor20

Okay,  so I recently realised my file fragment fix still breaks sometimes. If you reference a file like so:
```json
{
"$ref":"./potato.json#/definitions/leek"
}
```
it doesn't detect that it's a fragment, then joins it to the base fileURI and breaks 

This attempts to fix that. Currently It uses the most simple approach possible:
Split at a hash and error if there is more that one because we cannot tell what is fragment and what isn't

### Ideas to detect fragments better and support paths with hashes in them:
- anything after the last # if the uri doesn't end in a .json 
- any thing after a block of text that looks like '.json#/'
- 
Both of these are somewhat flawed. They don't work if you have combinations of the following:

- File paths and names can have hashes.
- files with json in them don't necessarily need to end in .json 

What are your thoughts on this? Maybe you can think of a better way.

2023-04-16 22:51 UTC, gregsdennis requested changes

2023-04-16 22:51 UTC, gregsdennis commented on JsonSchema/RefKeyword.cs
> +						$"Given a reference with more than one '#' in it. We cannot tell if this is a fragment, or where the fragment starts. Please don't use '#'s in fileNames or paths.\n Reference:{Reference.Origina
This is rather long.  I'd prefer a shorter error message with a longer explanation in the docs.

```suggestion
						"File references with multiple hashes are not supported.");
```

2023-04-16 23:06 UTC, gregsdennis requested changes

2023-04-16 23:06 UTC, gregsdennis commented on JsonSchema.Tests/ReferenceTests.cs
> +
Please remove this blank line.

2023-04-16 23:06 UTC, gregsdennis commented on JsonSchema.Tests/ReferenceTests.cs
> +
And this one.

2023-04-16 23:06 UTC, gregsdennis commented on JsonSchema.Tests/ReferenceTests.cs
Can you add a test to check that the exception is thrown, please?

2023-04-23 23:13 UTC, closed without merging

2023-04-23 23:25 UTC, faldor20 commented
Oh, haha, well I was just about to push my changes but If you've got a fix that's great. Hilarious timing though.
Do you want to integrate the unit tests I included into your branch, just to ensure your change works for my case?

2023-04-23 23:27 UTC, gregsdennis commented
Yes, that'd be great. Thanks.